### ISSUE TITLE
About the train_cifar.npy and test_cifar.npy

### ISSUE THREAD

**Issue by csjunjun** [Kira0096/CGAttack#4]

**Comment by Majboor** [comment]
I dont think he has provided it only this is given
`Download pre-trained model
Download the pretrained models and dataset [[download link]](https://drive.google.com/file/d/1WwclqsVxezicWHTZeif7HzwWUjCXCkyt/view?usp=sharing) and unzip it with

unzip pretrained.zip
Then you can conduct the untargeted attack for CIFAR-10 evaluation without training.`

**Comment by csjunjun** [comment]
Thank you very much. I eventually find that there is no useful meaning for this code"processed_y" in the RLearner.py . I thought I needed to use perturbations in the training data.
